In [15]:
import tensorflow as tf
import numpy as np

from prepare_dataset import _bytes_feature

In [3]:
# Vetor numpy
a = np.array([[2.12312, 3., 4.], [5., 6., 7.]], dtype=np.double)
a

array([[2.12312, 3.     , 4.     ],
       [5.     , 6.     , 7.     ]])

In [7]:
# Serializa para a_bstring, com uma coerção implícita de "a" para tensor no argumento.
a_bstring = tf.io.serialize_tensor(a)
a_bstring


<tf.Tensor: shape=(), dtype=string, numpy=b'\x08\x02\x12\x08\x12\x02\x08\x02\x12\x02\x08\x03"0@\xde\xabV&\xfc\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@'>

In [14]:
# (Forma de recuperar a)
tf.io.parse_tensor(a_bstring, out_type=tf.float64).numpy()

array([[2.12312, 3.     , 4.     ],
       [5.     , 6.     , 7.     ]])

In [9]:
# Cria o exemplo de treinamento com a_bstring como uma feature
example = tf.train.Example(features=tf.train.Features(feature={
    "array": _bytes_feature(a_bstring)
}))
example

features {
  feature {
    key: "array"
    value {
      bytes_list {
        value: "\010\002\022\010\022\002\010\002\022\002\010\003\"0@\336\253V&\374\000@\000\000\000\000\000\000\010@\000\000\000\000\000\000\020@\000\000\000\000\000\000\024@\000\000\000\000\000\000\030@\000\000\000\000\000\000\034@"
      }
    }
  }
}

In [10]:
# Serializa o exemplo para uma string.
string_example = example.SerializeToString()
string_example

b'\nM\nK\n\x05array\x12B\n@\n>\x08\x02\x12\x08\x12\x02\x08\x02\x12\x02\x08\x03"0@\xde\xabV&\xfc\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@'

In [12]:
# Forma de recuperar o exemplo serializado.
tf.train.Example.FromString(string_example)


features {
  feature {
    key: "array"
    value {
      bytes_list {
        value: "\010\002\022\010\022\002\010\002\022\002\010\003\"0@\336\253V&\374\000@\000\000\000\000\000\000\010@\000\000\000\000\000\000\020@\000\000\000\000\000\000\024@\000\000\000\000\000\000\030@\000\000\000\000\000\000\034@"
      }
    }
  }
}

In [13]:
# Forma de parsear o exemplo serializado para o a_bstring
parsed_example = tf.io.parse_example(
    string_example,
    features = {
        "array": tf.io.FixedLenFeature([], tf.string, default_value='')
    }
)
parsed_example

{'array': <tf.Tensor: shape=(), dtype=string, numpy=b'\x08\x02\x12\x08\x12\x02\x08\x02\x12\x02\x08\x03"0@\xde\xabV&\xfc\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@'>}

In [63]:
# Forma de recuperar a (repetida).
tf.io.parse_tensor(parsed_example["array"], out_type=tf.float64).numpy()

array([[2.12312, 3.     , 4.     ],
       [5.     , 6.     , 7.     ]])